<a href="https://colab.research.google.com/github/sidharth-ds/Data-Visualizations/blob/main/plotly_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import plotly.express as px
import plotly.graph_objects as go

# Subplots:

In [ ]:
from plotly.subplots import make_subplots

In [ ]:
fig = make_subplots(rows=3,cols=1,subplot_titles=('plot1','plot2','plot3'))

fig.append_trace(go.Scatter(x=[1,2,3,4,5,6,7,8,9],y=[69,141,213,285,357,429,501,573,645]),row=1,col=1)    
fig.append_trace(go.Scatter(x=[1,2,3,4,5,6,7,8,9],y=[69,141,213,285,357,-50,501,573,645]),row=2,col=1)
fig.append_trace(go.Scatter(x=[1,2,3,4,5,6,7,8,9],y=[69,141,213,1285,357,429,501,573,645]),row=3,col=1)

fig.update_layout(height=700,width=900,title_text='same subplot')
fig.show()

* instead of 'append_trace', we can use 'add_trace'
* xy : line/bar/scatter
* polar : barpolar, scatterpolar
* scene : 3d
* domain : pie, sunburst

In [ ]:
fig = make_subplots(rows=2,cols=2,subplot_titles=('plot1','plot2','plot3','plot4'),
                   specs=[
                          [{'type':'xy'},{'type':'polar'}],
                          [{'type':'scene'},{'type':'domain'}]
                          ]
                    )

fig.append_trace(go.Bar(x=[1,2,3,4,5,6,7,8,9],y=[69,141,213,285,357,429,501,573,645]),row=1,col=1)    
fig.append_trace(go.Barpolar(r=[1,2,3,4,5,6,7,8,9],theta=[69,141,213,285,357,429,501,573,645]),row=1,col=2)
fig.append_trace(go.Scatter3d(x=[1,2,3,4,5,6,7,8],y=[21,42,6,8,22,55,33,88],z=[53,6,75,8,14,63,75,35]),row=2,col=1)
fig.append_trace(go.Pie(values=[2,4,6,8]),row=2,col=2)

fig.update_layout(title_text="different subplot")
fig.show()

* changing starting point:

In [ ]:
fig = make_subplots(rows=2,cols=2,subplot_titles=('plot1','plot2','plot3','plot4'),start_cell='bottom-left')

fig.append_trace(go.Scatter(x=[1,2,3,4,5,6,7,8,9],y=[69,141,213,285,357,429,501,573,645]),row=1,col=1)    
fig.append_trace(go.Scatter(x=[1,2,3,4,5,6,7,8,9],y=[69,141,-213,285,357,429,2501,573,645]),row=1,col=2)
fig.append_trace(go.Scatter(x=[1,2,3,4],y=[69,141,-213,285],mode='markers+text',text=['pointA','pointB','pointC','pointD'],textposition='top right'),row=2,col=1)
fig.append_trace(go.Scatter(x=[1,2,3,4,5,6,7,8,9],y=[69,141,213,285,357,429,501,573,645]),row=2,col=2)

fig.update_layout(height=500,width=1000,title_text='changing starting point')
fig.show()

# creating Buttons:

In [ ]:
df = px.data.iris()
df.head()

sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [ ]:
fig = go.Figure(go.Scatter(x=df['sepal_length'],y=df['sepal_width'],mode='markers'))
fig.update_layout(
        updatemenus=[
                    dict(type='buttons',
                    direction='down',       # right/left/up
                    buttons=list([
                                  dict(args=['type','scatter'],
                                        label='scatter plot',
                                        method='restyle'),
                                  dict(args=['type','bar'],
                                        label='bar plot',
                                        method='restyle')
                                 ])
                         )
                      ]
                  )
fig.show()

In [ ]:
fig = go.Figure(data=[go.Scatter(x=df['sepal_length'],y=df['sepal_width'],mode='markers')])
fig.update_layout(
       updatemenus=[
                 dict(
                    direction='down',    # up/left/right
                    buttons=list([
                               dict(args=['type','scatter'],
                                    label='scatter plot',
                                    method='restyle'),
                               dict(args=['type','bar'],
                                    label='bar plot',
                                    method='restyle')
                               ]) 
                     )
                  ]
                )
fig.show()

# Animation:

In [ ]:
df3 = px.data.gapminder()
df3

country continent  year  ...   gdpPercap  iso_alpha  iso_num
0     Afghanistan      Asia  1952  ...  779.445314        AFG        4
1     Afghanistan      Asia  1957  ...  820.853030        AFG        4
2     Afghanistan      Asia  1962  ...  853.100710        AFG        4
3     Afghanistan      Asia  1967  ...  836.197138        AFG        4
4     Afghanistan      Asia  1972  ...  739.981106        AFG        4
...           ...       ...   ...  ...         ...        ...      ...
1699     Zimbabwe    Africa  1987  ...  706.157306        ZWE      716
1700     Zimbabwe    Africa  1992  ...  693.420786        ZWE      716
1701     Zimbabwe    Africa  1997  ...  792.449960        ZWE      716
1702     Zimbabwe    Africa  2002  ...  672.038623        ZWE      716
1703     Zimbabwe    Africa  2007  ...  469.709298        ZWE      716

[1704 rows x 8 columns]

In [ ]:
fig = px.bar(df3,x='continent',y='pop',animation_frame='year')
fig.show()

* hover_name : sub-component of x-axis values.
* range_y : y-axis min&max values

In [ ]:
fig = px.bar(df3,x='continent',y='pop',hover_name='country',color='gdpPercap',animation_frame='year',range_y=[0,4000000000])
fig.show()


# Candle Stick: (for stock markets)

In [ ]:
import pandas as pd

In [ ]:
dfx = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv')
dfx

Date   AAPL.Open   AAPL.High  ...        mavg          up   direction
0    2015-02-17  127.489998  128.880005  ...  117.927667  129.114281  Increasing
1    2015-02-18  127.629997  128.779999  ...  118.940333  130.038244  Increasing
2    2015-02-19  128.479996  129.029999  ...  119.889167  130.884089  Decreasing
3    2015-02-20  128.619995  129.500000  ...  120.763500  131.741551  Increasing
4    2015-02-23  130.020004  133.000000  ...  121.720167  133.067817  Increasing
..          ...         ...         ...  ...         ...         ...         ...
501  2017-02-10  132.460007  132.940002  ...  124.498666  134.503328  Decreasing
502  2017-02-13  133.080002  133.820007  ...  125.205166  135.589534  Increasing
503  2017-02-14  133.470001  135.089996  ...  125.953499  136.731280  Increasing
504  2017-02-15  135.520004  136.270004  ...  126.723499  137.901963  Decreasing
505  2017-02-16  135.669998  135.899994  ...  127.504332  138.805366  Decreasing

[506 rows x 11 columns]

In [ ]:
fig = go.Figure(go.Candlestick(x=dfx['Date'],open=dfx['AAPL.Open'],close=dfx['AAPL.Close'],high=dfx['AAPL.High'],low=dfx['AAPL.Low']))
fig.show()

* to turn-off rangeslider:

In [ ]:
fig = go.Figure(go.Candlestick(x=dfx['Date'],open=dfx['AAPL.Open'],close=dfx['AAPL.Close'],high=dfx['AAPL.High'],low=dfx['AAPL.Low']))

fig.update_layout(xaxis_rangeslider_visible=False)
fig.show()

* changing color:

In [ ]:
fig = go.Figure(go.Candlestick(x=dfx['Date'],open=dfx['AAPL.Open'],close=dfx['AAPL.Close'],high=dfx['AAPL.High'],low=dfx['AAPL.Low'],
                               increasing_line_color='cyan',decreasing_line_color='grey'))

fig.update_layout(xaxis_rangeslider_visible=False)
fig.show()

# scatter plot with buttons:

In [ ]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=dfx['Date'],y=dfx['AAPL.High']))

fig.show()

In [ ]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=dfx['Date'],y=dfx['AAPL.High']))

fig.update_layout(
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                          dict(count=1,label='1m',step='month',stepmode='backward'),
                          dict(count=6,label='6m',step='month',stepmode='backward'),
                          dict(count=1,label='YTD',step='year',stepmode='todate'),
                          dict(count=1,label='1y',step='year',stepmode='backward'),
                          dict(step='all')
                          ])
                ),rangeslider=dict(visible=True),type='date'
              )
            )

fig.show()

# Surface area graph:

In [ ]:
import numpy as np

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.linspace(-30,30,30)   # (startvalue, endvalue, size(equally spaced))

array([-30.        , -27.93103448, -25.86206897, -23.79310345,
       -21.72413793, -19.65517241, -17.5862069 , -15.51724138,
       -13.44827586, -11.37931034,  -9.31034483,  -7.24137931,
        -5.17241379,  -3.10344828,  -1.03448276,   1.03448276,
         3.10344828,   5.17241379,   7.24137931,   9.31034483,
        11.37931034,  13.44827586,  15.51724138,  17.5862069 ,
        19.65517241,  21.72413793,  23.79310345,  25.86206897,
        27.93103448,  30.        ])

In [ ]:
np.outer(4,1)

array([[4]])

In [ ]:
np.outer(4,[1,1])

array([[4, 4]])

In [ ]:
np.outer(4,[2,1])

array([[8, 4]])

In [ ]:
np.outer([4,5],[2,1])

array([[ 8,  4],
       [10,  5]])

In [ ]:
x = np.outer(np.linspace(-2,2,30),np.ones(30))
x

* transpose(T)-----(rows become columns, columns become rows)

In [ ]:
y = x.copy().T 
y

In [ ]:
z1 = np.sin(x**2 + y**2)  # square means surface  

In [ ]:
fig = go.Figure(data=[go.Surface(x=x,y=y,z=z1)])
fig.show()

In [ ]:
z2 = np.cos(x**2 + y**2)  

fig = go.Figure(data=[go.Surface(x=x,y=y,z=z2)])
fig.show()

In [ ]:
z3 = np.tan(x**2 + y**2) 
fig = go.Figure(data=[go.Surface(x=x,y=y,z=z3)])
fig.show()

# sin, cos :

In [ ]:
x = 20*np.random.random(100)
y = np.sin(x)

In [ ]:
fig = go.Figure(data=[go.Scatter(x=x,y=y,mode='markers')])  # mode must be markers
fig.show()

In [ ]:
fig = px.scatter(x=x,y=y)
fig.show()

In [ ]:
x = 20*np.random.random(100)
y = np.cos(x)
z = np.sin(x)

fig = px.scatter(x=x,y=y)
fig.show()
fig = px.scatter(x=x,y=z)
fig.show()

# Mesh3d:

In [ ]:
x = 20*np.random.random(100)
y = np.cos(x)
z = np.sin(x)

fig = go.Figure(data=[go.Mesh3d(x=x,y=y,z=z)])
fig.show()

In [ ]:
x = 100*np.random.random(1000)
y = np.cos(x)
z = np.sin(x)

fig = go.Figure(data=[go.Mesh3d(x=x,y=y,z=z,opacity=0.5)])
fig.show()